name: 'Push Docker image to Google Container Registry'
description: 'Builds, tags, and pushes a Docker image to Google Container Registry'
inputs:
  gcp_email:
    description: 'Email account to authenticate with Google Cloud'
    required: true
  gcp_token:
    description: 'Full token/credentials file to authenticate to Google Cloud'
    required: true
  gcp_project:
    description: 'Google Container Registry project (defaults to repository owner)'
    required: false
  image_name:
    description: 'Unqualified image name to tag (defaults to repository name)'
    required: false
  image_tag:
    description: 'Tag to apply to the image before pushing (defaults to "latest" on master, or branch/tag name otherwise)'
    required: false
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'